apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroinbox-message-ids
  # namespace: zeroinbox-api-dev
  labels:
    app: zeroinbox-message-ids
    version: "0.5.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeroinbox-message-ids
  template:
    metadata:
      labels:
        app: zeroinbox-message-ids
    spec:
      restartPolicy: Always
      containers:
        - name: zeroinbox-message-ids
          image: "gcr.io/zeroinbox-portfolio-project/zeroinbox-message-ids@sha256:e7d6232a06ec7c077b5a0205087de29a450d26c8991febf215c0b4b2fc5243c1"
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "300m"
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 9113
          #     httpHeaders:
          #     - name: health-check
          #       value: "true"
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          envFrom:
          - configMapRef:
              name: "zeroinbox-message-ids-config"
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: MONGO_URI
          - name: RABBIT_URL
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: RABBIT_URL