apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroinbox-message-ids
  # namespace: zeroinbox-api-dev
  labels:
    app: zeroinbox-message-ids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeroinbox-message-ids
  template:
    metadata:
      labels:
        app: zeroinbox-message-ids
    spec:
      restartPolicy: Always
      containers:
        - name: zeroinbox-message-ids
          image: "gcr.io/zeroinbox-portfolio-project/zeroinbox-message-ids@sha256:44098838ff8f01f60a266ac6f656cbf7e36add9007b75c3ee5de95891c69623b"
          imagePullPolicy: IfNotPresent
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "300m"
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 9113
          #     httpHeaders:
          #     - name: health-check
          #       value: "true"
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          envFrom:
          - configMapRef:
              name: "zeroinbox-message-ids-config"
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: MONGO_URI
          - name: RABBIT_URL
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: RABBIT_URL