apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeroinbox-message-ids
  # namespace: zeroinbox-api-dev
  labels:
    app: zeroinbox-message-ids
    version: "0.5.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeroinbox-message-ids
  template:
    metadata:
      labels:
        app: zeroinbox-message-ids
    spec:
      restartPolicy: Always
      containers:
        - name: zeroinbox-message-ids
          image: "gcr.io/zeroinbox-portfolio-project/zeroinbox-message-ids@sha256:893f9b569b723bfdace58ca29aa4ea57328cc90ca3d730a89d88f490d4d1c90a"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9113
              httpHeaders:
              - name: health-check
                value: "true"
            initialDelaySeconds: 10
            periodSeconds: 5
          envFrom:
          - configMapRef:
              name: "zeroinbox-message-ids-config"
          env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: MONGO_URI
          - name: RABBIT_URL
            valueFrom:
              secretKeyRef:
                name: zeroinbox-secrets
                key: RABBIT_URL