version: "3.8"
services:

  redis:
    container_name: redis
    image: redis:6.2.5
    # ports:
    #  - 6379:6379
    expose:
      - "6379"
    networks:
      - backend

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - "5672"
    networks:
      - backend

networks:
  backend:
    name: backend

