apiVersion: "v1"
kind: "Service"
metadata:
  name: "zeroinbox-redis"
  namespace: "default"
  labels:
    app: "zeroinbox-redis"
spec:
  type: "NodePort"
  selector:
    app: "zeroinbox-redis"
  ports:
  - protocol: "TCP"
    port: 6379
    targetPort: 6379